/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/account/info": {
    /**
     * Get account information
     * @description Retrieve the current account information including ID, name, and status.
     */
    get: operations["getAccountInfo"];
  };
  "/account/name": {
    /** Set account name */
    put: operations["setAccountName"];
  };
  "/account/picture": {
    /** Set account profile picture */
    post: operations["setAccountPicture"];
  };
  "/account/presence": {
    /** Set account presence */
    put: operations["setAccountPresence"];
  };
  "/account/status": {
    /** Set account status */
    put: operations["setAccountStatus"];
  };
  "/calls/{callId}/reject": {
    /** Reject an incoming call */
    put: operations["updateCallsReject"];
  };
  "/chats": {
    /** List all WhatsApp chats */
    get: operations["getChats"];
  };
  "/chats/{chatId}": {
    /** Get chat information */
    get: operations["getChat"];
    /** Delete chat */
    delete: operations["deleteChat"];
  };
  "/chats/{chatId}/presence": {
    /** Update chat presence */
    put: operations["setChatPresence"];
  };
  "/chats/{chatId}/ephemeral": {
    /** Set ephemeral message expiration */
    put: operations["updateChatEphemeral"];
  };
  "/chats/{chatId}/mute": {
    /** Mute chat */
    put: operations["updateChatMute"];
  };
  "/chats/{chatId}/pin": {
    /** Pin or unpin chat */
    put: operations["updateChatPin"];
  };
  "/chats/{chatId}/archive": {
    /** Archive or unarchive chat */
    put: operations["updateChatArchive"];
  };
  "/chats/{chatId}/read": {
    /** Mark chat as read */
    put: operations["markChatAsRead"];
  };
  "/contacts": {
    /** List all WhatsApp contacts */
    get: operations["getContacts"];
    /** Create a new WhatsApp contact */
    post: operations["createContact"];
  };
  "/contacts/{contactId}": {
    /** Get contact information */
    get: operations["getContact"];
    /** Update contact information */
    put: operations["updateContact"];
  };
  "/contacts/{contactId}/picture": {
    /** Get contact profile picture */
    get: operations["getContactsPicture"];
  };
  "/contacts/{contactId}/business": {
    /** Get contact business profile */
    get: operations["getContactsBusiness"];
  };
  "/contacts/{contactId}/fullName": {
    /** Update contact full name */
    put: operations["updateContactsFullname"];
  };
  "/contacts/{contactId}/presence": {
    /** Subscribe to contact presence updates */
    post: operations["createContactsPresence"];
  };
  "/groups": {
    /** List all WhatsApp groups */
    get: operations["getGroups"];
    /** Create a new WhatsApp group */
    post: operations["createGroup"];
  };
  "/groups/{groupId}": {
    /** Get group information */
    get: operations["getGroup"];
    /** Delete group */
    delete: operations["deleteGroup"];
  };
  "/groups/{groupId}/description": {
    /** Update group description */
    put: operations["setGroupsDescription"];
  };
  "/groups/{groupId}/name": {
    /** Update group name */
    put: operations["setGroupsName"];
  };
  "/groups/{groupId}/picture": {
    /** Set group picture */
    post: operations["createGroupsPicture"];
  };
  "/groups/{groupId}/invite-link": {
    /** Get group invite link */
    get: operations["getGroupInviteLink"];
  };
  "/groups/{groupId}/requests": {
    /** List group invite requests */
    get: operations["getGroupsRequests"];
  };
  "/groups/{groupId}/participants": {
    /** Update group participants */
    put: operations["updateGroupsParticipants"];
  };
  "/group-invites/{inviteCode}": {
    /** Get group invite information */
    get: operations["getGroupInviteInfo"];
  };
  "/instance/settings": {
    /** Get instance settings */
    get: operations["getInstanceSettings"];
    /** Update instance settings */
    put: operations["updateInstanceSettings"];
  };
  "/instance/apikey": {
    /** Update instance API key */
    put: operations["updateApiKey"];
  };
  "/instance/restart": {
    /** Restart instance */
    put: operations["restartInstance"];
  };
  "/media/download": {
    /**
     * Download media file
     * @description Download a media file that was received. The id corresponds to the media.id field.
     */
    get: operations["getMediaDownload"];
  };
  "/messages/text": {
    /**
     * Send a text message
     * @description Send a text message to a WhatsApp contact or group. The response contains the MessageID, that can be used later for different actions, like reply, delete, forward, star, etc.
     */
    post: operations["sendTextMessage"];
  };
  "/messages/link": {
    /**
     * Send a link message
     * @description Send a link message to a WhatsApp contact or group. The url contains the link. It can also contain a title and description and additionally a thumbnail (jpeg base64 encoded). The response contains the MessageID
     */
    post: operations["sendLinkMessage"];
  };
  "/messages/image": {
    /**
     * Send an image message
     * @description Send an image message to a WhatsApp contact or group. The image can be sent as a URL (that will be downloaded and sent as an image) or as a base64 encoded string. The response contains the MessageID.
     */
    post: operations["sendImageMessage"];
  };
  "/messages/video": {
    /**
     * Send a video message
     * @description Send a video message to a WhatsApp contact or group. The video can be sent as a URL (that will be downloaded and sent as a video) or as a base64 encoded string. The response contains the MessageID.
     */
    post: operations["sendVideoMessage"];
  };
  "/messages/sticker": {
    /**
     * Send a sticker message
     * @description Send a sticker message to a WhatsApp contact or group. The sticker can be sent as a URL (that will be downloaded and sent as a sticker) or as a base64 encoded string. The response contains the MessageID.
     */
    post: operations["sendStickerMessage"];
  };
  "/messages/audio": {
    /** Send an audio message */
    post: operations["sendAudioMessage"];
  };
  "/messages/voice": {
    /** Send a voice message */
    post: operations["sendVoiceMessage"];
  };
  "/messages/document": {
    /** Send a document message */
    post: operations["sendDocumentMessage"];
  };
  "/messages/contact": {
    /** Send a contact message */
    post: operations["sendContactMessage"];
  };
  "/messages/location": {
    /** Send a location message */
    post: operations["sendLocationMessage"];
  };
  "/messages/{messageId}/reaction": {
    /** Send a reaction to a message */
    post: operations["sendReactionMessage"];
  };
  "/messages/{messageId}/text": {
    /** Edit a text message */
    put: operations["updateMessagesText"];
  };
  "/messages/{messageId}/read": {
    /** Mark a message as read */
    put: operations["updateMessagesRead"];
  };
  "/messages/{messageId}/star": {
    /** Star a message */
    put: operations["updateMessagesStar"];
  };
  "/messages/{messageId}/delete": {
    /** Delete a message */
    put: operations["updateMessagesDelete"];
  };
  "/messages/{messageId}/delete/forme": {
    /** Delete a message for me only */
    put: operations["updateMessagesDeleteForme"];
  };
  "/session/login/qr/image": {
    /**
     * Get QR code image for WhatsApp login
     * @description Retrieve the QR code image for logging into WhatsApp. The image can be displayed to the user for scanning.
     */
    get: operations["getSessionLoginQrImage"];
  };
  "/session/login/qr/code": {
    /** Get QR code string for WhatsApp login */
    get: operations["getSessionLoginQrCode"];
  };
  "/session/login/code/{phone}": {
    /**
     * Get login code for WhatsApp
     * @description Retrieve the login code for the specified phone number. The code should be used in the Whatsapp app link process.
     */
    get: operations["getSessionLoginCode"];
  };
  "/session/status": {
    /** Get WhatsApp session status */
    get: operations["getSessionStatus"];
  };
  "/session/logout": {
    /** Logout from WhatsApp */
    post: operations["createSessionLogout"];
  };
  "/users/{phone}": {
    /** Get user information */
    get: operations["getUser"];
  };
}


export interface components {
  schemas: {
    Error: {
      /** @description A URI reference that identifies the problem type */
      type: string;
      /** @description A short, human-readable summary of the problem type */
      title: string;
      /** @description The HTTP status code generated by the origin server for this occurrence of the problem */
      status: number;
      /** @description A human-readable explanation specific to this occurrence of the problem */
      detail: string;
    };
    SessionStatusResponse: {
      /** @description Whether the client is connected to WhatsApp */
      connected?: boolean;
      /** @description Whether the client is logged in */
      isLoggedIn?: boolean;
    };
    GeneratePairCodeResponse: {
      /** @description The generated pair code */
      code?: string;
    };
    GenerateQRCodeResponse: {
      /** @description The generated QR code */
      qrCode?: string;
    };
    InstanceSettings: {
      /** @description The name of the instance */
      name?: string;
      /** @description The description of the instance */
      description?: string;
      /** @description Whether to use pull mode for events */
      pullMode?: boolean;
    };
    InstanceSettingsRequest: {
      /** @description The name of the instance */
      name?: string;
      /** @description The description of the instance */
      description?: string;
      /** @description Whether to use pull mode for events */
      pullMode?: boolean;
    };
    SendTextRequest: {
      /** @description Recipient's contact number or group. For contacts it should be the full phone number and can include the whatsapp subfix (e.g. 1234567890@s.whatsapp.net). For groups should contain the groups subfix (e.g. 123456789012344555234@g.us). */
      to: string;
      /** @description Message text content */
      text: string;
      /** @description List of mentioned phone numbers. The numbers included in this list should be referenced as @<number> in the message text. (e.g. "Hello @1234567890"). */
      mentions?: string[];
      /** @description ID of the message being replied to */
      replyTo?: string;
      /** @description Whether the message is forwarded (if true, it will be marked as forwarded in WhatsApp) */
      isForwarded?: boolean;
    };
    SendLinkRequest: {
      to: string;
      text: string;
      url: string;
      title?: string;
      description?: string;
      /** Format: byte */
      jpegThumbnail?: string;
      mentions?: string[];
      replyTo?: string;
      isForwarded?: boolean;
    };
    SendImageRequest: {
      to: string;
      /** Format: byte */
      imageBase64?: string;
      imageURL?: string;
      mimeType: string;
      caption?: string;
      mentions?: string[];
      replyTo?: string;
      isForwarded?: boolean;
      viewOnce?: boolean;
    };
    SendVideoRequest: {
      /** @description Recipient's contact number or group. For contacts it should be the full phone number and can include the whatsapp subfix (e.g. 1234567890@s.whatsapp.net). For groups should contain the groups subfix (e.g. 123456789012344555234@g.us). */
      to: string;
      /**
       * Format: byte
       * @description Base64 encoded video content. This field is required if videoURL is not provided.
       */
      videoBase64?: string;
      /** @description URL of the video. This field is required if videoBase64 is not provided. */
      videoURL?: string;
      /** @description MIME type of the video (e.g. "video/mp4"). */
      mimeType: string;
      /** @description Caption for the video. It's displayed below the video in the chat. */
      caption?: string;
      /** @description Whether the video should be sent as a view once message (if true, the video will disappear after being viewed). */
      viewOnce?: boolean;
      /** @description List of mentioned phone numbers. The numbers included in this list should be referenced as @<number> in the message text. (e.g. "Hello @1234567890"). */
      mentions?: string[];
      /** @description ID of the message being replied to */
      replyTo?: string;
      /** @description Whether the message is forwarded (if true, it will be marked as forwarded in WhatsApp) */
      isForwarded?: boolean;
    };
    SendAudioRequest: {
      to: string;
      /** Format: byte */
      audioBase64?: string;
      audioURL?: string;
      mimeType: string;
      mentions?: string[];
      replyTo?: string;
      isForwarded?: boolean;
      viewOnce?: boolean;
    };
    SendVoiceRequest: {
      to: string;
      /** Format: byte */
      voiceBase64?: string;
      voiceURL?: string;
      mentions?: string[];
      replyTo?: string;
      isForwarded?: boolean;
      viewOnce?: boolean;
    };
    SendDocumentRequest: {
      to: string;
      /** Format: byte */
      documentBase64?: string;
      documentURL?: string;
      fileName: string;
      caption?: string;
      mentions?: string[];
      replyTo?: string;
      isForwarded?: boolean;
    };
    SendStickerRequest: {
      /** @description Recipient's contact number or group. For contacts it should be the full phone number and can include the whatsapp subfix (e.g. 1234567890@s.whatsapp.net). For groups should contain the groups subfix (e.g. 123456789012344555234@g.us). */
      to: string;
      /** Format: byte */
      stickerBase64?: string;
      stickerURL?: string;
      mimeType: string;
      isAnimated?: boolean;
      /** @description List of mentioned phone numbers. The numbers included in this list should be referenced as @<number> in the message text. (e.g. "Hello @1234567890"). */
      mentions?: string[];
      /** @description ID of the message being replied to */
      replyTo?: string;
      /** @description Whether the message is forwarded (if true, it will be marked as forwarded in WhatsApp) */
      isForwarded?: boolean;
    };
    SendReactionRequest: {
      to: string;
      senderId: string;
      reaction: string;
    };
    SendContactRequest: {
      to: string;
      /** @description Display name for the contact. Required if vCard is not provided. */
      displayName?: string;
      /** @description Raw vCard string. Required if displayName is not provided. */
      vCard?: string;
      mentions?: string[];
      replyTo?: string;
      isForwarded?: boolean;
    };
    SendLocationRequest: {
      to: string;
      /** Format: float */
      latitude: number;
      /** Format: float */
      longitude: number;
      name?: string;
      address?: string;
      url?: string;
    };
    MarkMessageAsReadRequest: {
      chatId: string;
      senderId: string;
      /** @enum {string} */
      receiptType: "delivered" | "sender" | "read" | "played";
    };
    StarMessageRequest: {
      chatId: string;
      senderId: string;
    };
    RejectCallRequest: {
      /** @description JID of the call creator */
      callerId: string;
    };
    DeleteMessageRequest: {
      /** @description ID of the chat containing the message */
      chatId: string;
      /** @description ID of the message sender */
      senderId: string;
    };
    DeleteMessageForMeRequest: {
      /** @description ID of the chat containing the message */
      chatId: string;
      /** @description ID of the message sender */
      senderId: string;
      /** @description If the message to delete is from the sender */
      ifFromMe: boolean;
      /**
       * Format: date-time
       * @description Time when the message was sent (could be aproximate, but is required)
       */
      Time: string;
    };
    ChatInfo: {
      /** @description Chat JID */
      id: string;
      /** @description LID associated with the chat when available */
      lid?: string | null;
      /** @description Indicates whether the chat is read-only */
      isReadOnly: boolean;
      /** @description Indicates whether the chat is a group chat */
      isGroup: boolean;
      /** @description Indicates whether the chat is archived */
      isArchived: boolean;
      /** @description Indicates whether the chat is pinned */
      isPinned: boolean;
      /** @description Indicates whether ephemeral messages are enabled */
      isEphemeral: boolean;
      /**
       * @description Ephemeral message expiration policy
       * @enum {string|null}
       */
      ephemeralExpiration?: "off" | "24h" | "7d" | "90d" | null;
      /** @description Indicates whether the chat is muted */
      isMuted: boolean;
      /**
       * Format: date-time
       * @description When the mute configuration expires, if applicable
       */
      muteEndTime?: string | null;
      /** @description Indicates whether the chat is flagged as spam */
      isSpam: boolean;
    };
    ContactInfo: {
      /** @description Contact JID */
      id: string;
      /** @description LID associated with the contact when available */
      lid?: string | null;
      /** @description Contact full name */
      fullName: string;
      /** @description Contact business name */
      businessName: string;
      /** @description Contact push name */
      pushName: string;
      /** @description Contact status message */
      status: string;
      /** @description Current profile picture identifier */
      pictureId: string;
      /** @description Indicates if the contact is in the phone address book */
      inPhoneAddressBook: boolean;
    };
    ContactBusinessProfile: {
      /** @description Business profile identifier */
      id: string;
      /** @description Physical address of the business */
      address: string;
      /** @description Business description */
      description: string;
      /** @description Contact email address for the business */
      email: string;
      /** @description Business website URL */
      website: string;
      /**
       * Format: double
       * @description Latitude of the business location
       */
      latitude: number;
      /**
       * Format: double
       * @description Longitude of the business location
       */
      longitude: number;
      /** @description Date when the business joined WhatsApp */
      memberSince: string;
      /** @description Categories associated with the business */
      categories: components["schemas"]["ContactBusinessCategory"][];
      /** @description Time zone used for the business hours */
      businessHoursTimeZone: string;
      /** @description Opening hours for the business */
      businessHours: components["schemas"]["BusinessHours"][];
      /** @description Additional profile options represented as key-value pairs */
      profileOptions: {
        [key: string]: string;
      };
    };
    ContactBusinessCategory: {
      /** @description Category identifier */
      id: string;
      /** @description Category display name */
      name: string;
    };
    BusinessHours: {
      /** @description Day of the week the schedule applies to */
      dayOfWeek: string;
      /** @description Business hours mode (for example OPEN or CLOSED) */
      mode: string;
      /** @description Opening time in HH:mm format */
      openTime: string;
      /** @description Closing time in HH:mm format */
      closeTime: string;
    };
    ContactPicture: {
      /** @description Identifier of the contact picture */
      pictureId: string;
      /** @description Download URL for the contact picture */
      pictureUrl: string;
    };
  };
  responses: never;
  parameters: {
    /** @description The ID of the WhatsApp instance */
    InstanceIdHeader: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Get account information
   * @description Retrieve the current account information including ID, name, and status.
   */
  getAccountInfo: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
    };
    responses: {
      /** @description Account information */
      200: {
        content: {
          "application/json": {
            /** @description Account ID */
            jid?: string;
            /** @description Account name */
            name?: string;
            /** @description Account status */
            status?: string;
          };
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Set account name */
  setAccountName: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
    };
    requestBody: {
      content: {
        "application/json": {
          /** @description New account name */
          name: string;
        };
      };
    };
    responses: {
      /** @description Account name updated successfully */
      204: {
        content: never;
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Set account profile picture */
  setAccountPicture: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
    };
    requestBody: {
      content: {
        "application/json": {
          /** @description Base64 encoded image data */
          pictureBase64: string;
        };
      };
    };
    responses: {
      /** @description Profile picture updated successfully */
      201: {
        content: {
          "application/json": {
            /** @description Picture ID */
            id?: string;
          };
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Set account presence */
  setAccountPresence: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
    };
    requestBody: {
      content: {
        "application/json": {
          /**
           * @description Presence status
           * @enum {string}
           */
          status: "available" | "unavailable";
        };
      };
    };
    responses: {
      /** @description Presence updated successfully */
      204: {
        content: never;
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Set account status */
  setAccountStatus: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
    };
    requestBody: {
      content: {
        "application/json": {
          /** @description Account status message */
          status: string;
        };
      };
    };
    responses: {
      /** @description Status updated successfully */
      204: {
        content: never;
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Reject an incoming call */
  updateCallsReject: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
      path: {
        callId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RejectCallRequest"];
      };
    };
    responses: {
      /** @description Call rejected successfully */
      204: {
        content: never;
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** List all WhatsApp chats */
  getChats: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
    };
    responses: {
      /** @description List of chats */
      200: {
        content: {
          "application/json": components["schemas"]["ChatInfo"][];
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Get chat information */
  getChat: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
      path: {
        chatId: string;
      };
    };
    responses: {
      /** @description Chat information */
      200: {
        content: {
          "application/json": components["schemas"]["ChatInfo"];
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Delete chat */
  deleteChat: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
      path: {
        chatId: string;
      };
    };
    responses: {
      /** @description Chat deleted successfully */
      204: {
        content: never;
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Update chat presence */
  setChatPresence: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
      path: {
        chatId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          /**
           * @description Presence state
           * @enum {string}
           */
          state: "typing" | "recording" | "paused";
        };
      };
    };
    responses: {
      /** @description Presence updated successfully */
      204: {
        content: never;
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Set ephemeral message expiration */
  updateChatEphemeral: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
      path: {
        chatId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          /**
           * @description Message expiration time
           * @enum {string}
           */
          ephemeralExpiration: "off" | "24h" | "7d" | "90d";
        };
      };
    };
    responses: {
      /** @description Ephemeral expiration set successfully */
      204: {
        content: never;
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Mute chat */
  updateChatMute: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
      path: {
        chatId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          /** @description Duration preset for muting the chat (for example '8h', '1w', 'always'); omit or set to null to unmute */
          duration?: string | null;
        };
      };
    };
    responses: {
      /** @description Chat muted successfully */
      204: {
        content: never;
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Pin or unpin chat */
  updateChatPin: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
      path: {
        chatId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          /** @description Whether to pin or unpin the chat */
          pinned: boolean;
        };
      };
    };
    responses: {
      /** @description Chat pin status updated successfully */
      204: {
        content: never;
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Archive or unarchive chat */
  updateChatArchive: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
      path: {
        chatId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          /** @description Whether to archive or unarchive the chat */
          archived: boolean;
        };
      };
    };
    responses: {
      /** @description Chat archive status updated successfully */
      204: {
        content: never;
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Mark chat as read */
  markChatAsRead: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
      path: {
        chatId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          /** @description Whether to mark the chat as read */
          read: boolean;
        };
      };
    };
    responses: {
      /** @description Chat marked as read successfully */
      204: {
        content: never;
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** List all WhatsApp contacts */
  getContacts: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
    };
    responses: {
      /** @description List of contacts */
      200: {
        content: {
          "application/json": components["schemas"]["ContactInfo"][];
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Create a new WhatsApp contact */
  createContact: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
    };
    requestBody: {
      content: {
        "application/json": {
          /** @description Contact ID */
          id: string;
          /** @description Contact's full name */
          fullName: string;
          /** @description Contact's first name */
          firstName: string;
        };
      };
    };
    responses: {
      /** @description Contact created successfully */
      204: {
        content: never;
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Get contact information */
  getContact: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
      path: {
        contactId: string;
      };
    };
    responses: {
      /** @description Contact information */
      200: {
        content: {
          "application/json": components["schemas"]["ContactInfo"];
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Update contact information */
  updateContact: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
      path: {
        contactId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          /** @description Contact's full name */
          fullName: string;
          /** @description Contact's first name */
          firstName: string;
        };
      };
    };
    responses: {
      /** @description Contact updated successfully */
      204: {
        content: never;
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Get contact profile picture */
  getContactsPicture: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
      path: {
        contactId: string;
      };
    };
    responses: {
      /** @description Contact profile picture */
      200: {
        content: {
          "application/json": components["schemas"]["ContactPicture"];
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Get contact business profile */
  getContactsBusiness: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
      path: {
        contactId: string;
      };
    };
    responses: {
      /** @description Business profile information */
      200: {
        content: {
          "application/json": components["schemas"]["ContactBusinessProfile"];
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Update contact full name */
  updateContactsFullname: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
      path: {
        contactId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          /** @description New full name for the contact */
          fullName: string;
        };
      };
    };
    responses: {
      /** @description Contact name updated successfully */
      204: {
        content: never;
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Subscribe to contact presence updates */
  createContactsPresence: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
      path: {
        contactId: string;
      };
    };
    responses: {
      /** @description Successfully subscribed to presence updates */
      204: {
        content: never;
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** List all WhatsApp groups */
  getGroups: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
    };
    responses: {
      /** @description List of groups */
      200: {
        content: {
          "application/json": {
              /** @description Group ID */
              id?: string;
              /** @description Group name */
              name?: string;
              /** @description Group description */
              description?: string;
              /** @description Group picture URL */
              picture?: string;
              /** @description Group invite link */
              inviteLink?: string;
              participants?: string[];
            }[];
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Create a new WhatsApp group */
  createGroup: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
    };
    requestBody: {
      content: {
        "application/json": {
          /** @description Group name */
          name: string;
          participants: string[];
        };
      };
    };
    responses: {
      /** @description Group created successfully */
      201: {
        content: {
          "application/json": {
            /** @description Group ID */
            id?: string;
          };
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Get group information */
  getGroup: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
      path: {
        groupId: string;
      };
    };
    responses: {
      /** @description Group information */
      200: {
        content: {
          "application/json": {
            /** @description Group ID */
            id?: string;
            /** @description Group name */
            name?: string;
            /** @description Group description */
            description?: string;
            /** @description Group picture URL */
            picture?: string;
            /** @description Group invite link */
            inviteLink?: string;
            participants?: string[];
          };
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Delete group */
  deleteGroup: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
      path: {
        groupId: string;
      };
    };
    responses: {
      /** @description Group deleted successfully */
      204: {
        content: never;
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Update group description */
  setGroupsDescription: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
      path: {
        groupId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          /** @description New group description */
          description: string;
        };
      };
    };
    responses: {
      /** @description Group description updated successfully */
      204: {
        content: never;
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Update group name */
  setGroupsName: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
      path: {
        groupId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          /** @description New group name */
          name: string;
        };
      };
    };
    responses: {
      /** @description Group name updated successfully */
      204: {
        content: never;
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Set group picture */
  createGroupsPicture: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
      path: {
        groupId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          /** @description Base64 encoded image data */
          pictureBase64: string;
        };
      };
    };
    responses: {
      /** @description Group picture updated successfully */
      201: {
        content: {
          "application/json": {
            /** @description Picture ID */
            id?: string;
          };
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Get group invite link */
  getGroupInviteLink: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
      path: {
        groupId: string;
      };
    };
    responses: {
      /** @description Group invite link */
      200: {
        content: {
          "application/json": string;
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** List group invite requests */
  getGroupsRequests: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
      path: {
        groupId: string;
      };
    };
    responses: {
      /** @description List of invite requests */
      200: {
        content: {
          "application/json": string[];
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Update group participants */
  updateGroupsParticipants: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
      path: {
        groupId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          participants: string[];
        };
      };
    };
    responses: {
      /** @description Group participants updated successfully */
      204: {
        content: never;
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Get group invite information */
  getGroupInviteInfo: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
      path: {
        inviteCode: string;
      };
    };
    responses: {
      /** @description Group invite information */
      200: {
        content: {
          "application/json": {
            /** @description Invite code */
            code?: string;
            /** @description Group ID */
            group?: string;
            /** @description Invite expiration date */
            expires?: string;
          };
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Get instance settings */
  getInstanceSettings: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
    };
    responses: {
      /** @description Instance settings */
      200: {
        content: {
          "application/json": components["schemas"]["InstanceSettings"];
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Update instance settings */
  updateInstanceSettings: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InstanceSettingsRequest"];
      };
    };
    responses: {
      /** @description Instance settings */
      200: {
        content: {
          "application/json": components["schemas"]["InstanceSettings"];
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Update instance API key */
  updateApiKey: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
    };
    responses: {
      /** @description Instance settings */
      200: {
        content: {
          "application/json": string;
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Restart instance */
  restartInstance: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
    };
    responses: {
      /** @description Instance restarted successfully */
      204: {
        content: never;
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /**
   * Download media file
   * @description Download a media file that was received. The id corresponds to the media.id field.
   */
  getMediaDownload: {
    parameters: {
      query: {
        /** @description The ID of the media file to download */
        id: string;
      };
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
    };
    responses: {
      /** @description Media file */
      200: {
        content: {
          "application/octet-stream": string;
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /**
   * Send a text message
   * @description Send a text message to a WhatsApp contact or group. The response contains the MessageID, that can be used later for different actions, like reply, delete, forward, star, etc.
   */
  sendTextMessage: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SendTextRequest"];
      };
    };
    responses: {
      /** @description Message sent successfully */
      201: {
        content: {
          "application/json": {
            /** @description Unique message ID */
            id?: string;
          };
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /**
   * Send a link message
   * @description Send a link message to a WhatsApp contact or group. The url contains the link. It can also contain a title and description and additionally a thumbnail (jpeg base64 encoded). The response contains the MessageID
   */
  sendLinkMessage: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SendLinkRequest"];
      };
    };
    responses: {
      /** @description Link message sent successfully */
      201: {
        content: {
          "application/json": {
            id?: string;
          };
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /**
   * Send an image message
   * @description Send an image message to a WhatsApp contact or group. The image can be sent as a URL (that will be downloaded and sent as an image) or as a base64 encoded string. The response contains the MessageID.
   */
  sendImageMessage: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SendImageRequest"];
      };
    };
    responses: {
      /** @description Image message sent successfully */
      201: {
        content: {
          "application/json": {
            id?: string;
          };
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /**
   * Send a video message
   * @description Send a video message to a WhatsApp contact or group. The video can be sent as a URL (that will be downloaded and sent as a video) or as a base64 encoded string. The response contains the MessageID.
   */
  sendVideoMessage: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SendVideoRequest"];
      };
    };
    responses: {
      /** @description Video message sent successfully */
      201: {
        content: {
          "application/json": {
            id?: string;
          };
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /**
   * Send a sticker message
   * @description Send a sticker message to a WhatsApp contact or group. The sticker can be sent as a URL (that will be downloaded and sent as a sticker) or as a base64 encoded string. The response contains the MessageID.
   */
  sendStickerMessage: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SendStickerRequest"];
      };
    };
    responses: {
      /** @description Sticker message sent successfully */
      201: {
        content: {
          "application/json": {
            id?: string;
          };
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Send an audio message */
  sendAudioMessage: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SendAudioRequest"];
      };
    };
    responses: {
      /** @description Audio message sent successfully */
      201: {
        content: {
          "application/json": {
            id?: string;
          };
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Send a voice message */
  sendVoiceMessage: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SendVoiceRequest"];
      };
    };
    responses: {
      /** @description Voice message sent successfully */
      201: {
        content: {
          "application/json": {
            id?: string;
          };
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Send a document message */
  sendDocumentMessage: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SendDocumentRequest"];
      };
    };
    responses: {
      /** @description Document message sent successfully */
      201: {
        content: {
          "application/json": {
            id?: string;
          };
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Send a contact message */
  sendContactMessage: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SendContactRequest"];
      };
    };
    responses: {
      /** @description Contact message sent successfully */
      201: {
        content: {
          "application/json": {
            id?: string;
          };
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Send a location message */
  sendLocationMessage: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SendLocationRequest"];
      };
    };
    responses: {
      /** @description Location message sent successfully */
      201: {
        content: {
          "application/json": {
            id?: string;
          };
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Send a reaction to a message */
  sendReactionMessage: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
      path: {
        messageId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SendReactionRequest"];
      };
    };
    responses: {
      /** @description Reaction sent successfully */
      201: {
        content: {
          "application/json": {
            id?: string;
          };
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Edit a text message */
  updateMessagesText: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
      path: {
        messageId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SendTextRequest"];
      };
    };
    responses: {
      /** @description Message edited successfully */
      201: {
        content: {
          "application/json": {
            id?: string;
          };
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Mark a message as read */
  updateMessagesRead: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
      path: {
        messageId: string;
      };
    };
    requestBody: {
      content: {
        /**
         * @example {
         *   "chatId": "1234567890@s.whatsapp.net",
         *   "senderId": "1234567890@s.whatsapp.net",
         *   "receiptType": "read"
         * }
         */
        "application/json": components["schemas"]["MarkMessageAsReadRequest"];
      };
    };
    responses: {
      /** @description Message marked as read successfully */
      200: {
        content: never;
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Star a message */
  updateMessagesStar: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
      path: {
        messageId: string;
      };
    };
    requestBody: {
      content: {
        /**
         * @example {
         *   "chatId": "1234567890@s.whatsapp.net",
         *   "senderId": "1234567890@s.whatsapp.net"
         * }
         */
        "application/json": components["schemas"]["StarMessageRequest"];
      };
    };
    responses: {
      /** @description Message starred successfully */
      200: {
        content: never;
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Delete a message */
  updateMessagesDelete: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
      path: {
        messageId: string;
      };
    };
    requestBody: {
      content: {
        /**
         * @example {
         *   "chatId": "1234567890@s.whatsapp.net",
         *   "senderId": "1234567890@s.whatsapp.net"
         * }
         */
        "application/json": components["schemas"]["DeleteMessageRequest"];
      };
    };
    responses: {
      /** @description Message deleted successfully */
      200: {
        content: never;
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Delete a message for me only */
  updateMessagesDeleteForme: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
      path: {
        messageId: string;
      };
    };
    requestBody: {
      content: {
        /**
         * @example {
         *   "chatId": "1234567890@s.whatsapp.net",
         *   "senderId": "1234567890@s.whatsapp.net",
         *   "ifFromMe": true,
         *   "Time": "2025-05-19T00:51:44.816Z"
         * }
         */
        "application/json": components["schemas"]["DeleteMessageForMeRequest"];
      };
    };
    responses: {
      /** @description Message deleted for me successfully */
      200: {
        content: never;
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /**
   * Get QR code image for WhatsApp login
   * @description Retrieve the QR code image for logging into WhatsApp. The image can be displayed to the user for scanning.
   */
  getSessionLoginQrImage: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
    };
    responses: {
      /** @description QR code image */
      200: {
        content: {
          "image/png": string;
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Get QR code string for WhatsApp login */
  getSessionLoginQrCode: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
    };
    responses: {
      /** @description QR code string */
      200: {
        content: {
          "application/json": components["schemas"]["GenerateQRCodeResponse"];
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /**
   * Get login code for WhatsApp
   * @description Retrieve the login code for the specified phone number. The code should be used in the Whatsapp app link process.
   */
  getSessionLoginCode: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
      path: {
        phone: string;
      };
    };
    responses: {
      /** @description Login code */
      200: {
        content: {
          "application/json": components["schemas"]["GeneratePairCodeResponse"];
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Get WhatsApp session status */
  getSessionStatus: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
    };
    responses: {
      /** @description Session status */
      200: {
        content: {
          "application/json": components["schemas"]["SessionStatusResponse"];
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Logout from WhatsApp */
  createSessionLogout: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
    };
    responses: {
      /** @description Logged out successfully */
      204: {
        content: never;
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /** Get user information */
  getUser: {
    parameters: {
      header: {
        "X-Instance-Id": components["parameters"]["InstanceIdHeader"];
      };
      path: {
        phone: string;
      };
    };
    responses: {
      /** @description User information */
      200: {
        content: {
          "application/json": {
            /** @description User JID */
            jid?: string;
            /** @description User name */
            name?: string;
            /** @description User status */
            status?: string;
          };
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
}
